let dataGeneralxsku = [
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMI12CABWCCC8",
      sinInteraccion: "3,702",
      conInteraccion: 385,
      tiempoSinInteraccion: "0:03:28",
      tiempoConInteraccion: "0:06:53",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "21%",
      TransaccionesSinInteraccion: 0.0054,
      TransaccionesConInteraccion: 0.0078,
      Mes: "Febrero"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "PTM12CABWJM2",
      sinInteraccion: "2,677",
      conInteraccion: 321,
      tiempoSinInteraccion: "0:03:17",
      tiempoConInteraccion: "0:07:03",
      AddToCartSinInteraccion: "10%",
      AddToCartConInteraccion: "12%",
      TransaccionesSinInteraccion: 0.0034,
      TransaccionesConInteraccion: 0.0062,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMI12CDBWCCC8",
      sinInteraccion: "1,983",
      conInteraccion: 210,
      tiempoSinInteraccion: "0:03:40",
      tiempoConInteraccion: "0:05:50",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "12%",
      TransaccionesSinInteraccion: 0.001,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMT12CABWCCC8",
      sinInteraccion: "1,482",
      conInteraccion: 203,
      tiempoSinInteraccion: "0:04:32",
      tiempoConInteraccion: "0:12:39",
      AddToCartSinInteraccion: "25%",
      AddToCartConInteraccion: "21%",
      TransaccionesSinInteraccion: 0.002,
      TransaccionesConInteraccion: 0.0049,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMI09CABWCCC8",
      sinInteraccion: "1,598",
      conInteraccion: 163,
      tiempoSinInteraccion: "0:03:33",
      tiempoConInteraccion: "0:09:22",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "18%",
      TransaccionesSinInteraccion: 0.0019,
      TransaccionesConInteraccion: 0.0061,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMT09CABWCCC8",
      sinInteraccion: "1,002",
      conInteraccion: 125,
      tiempoSinInteraccion: "0:04:03",
      tiempoConInteraccion: "0:03:46",
      AddToCartSinInteraccion: "27%",
      AddToCartConInteraccion: "22%",
      TransaccionesSinInteraccion: 0.004,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMT12CDBWCCC8",
      sinInteraccion: 807,
      conInteraccion: 89,
      tiempoSinInteraccion: "0:03:17",
      tiempoConInteraccion: "0:05:29",
      AddToCartSinInteraccion: "26%",
      AddToCartConInteraccion: "31%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMI24CDBWCCC8",
      sinInteraccion: 715,
      conInteraccion: 79,
      tiempoSinInteraccion: "0:03:15",
      tiempoConInteraccion: "0:02:50",
      AddToCartSinInteraccion: "17%",
      AddToCartConInteraccion: "15%",
      TransaccionesSinInteraccion: 0.0014,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMI18CDBWCCC8",
      sinInteraccion: 527,
      conInteraccion: 50,
      tiempoSinInteraccion: "0:04:37",
      tiempoConInteraccion: "0:18:16",
      AddToCartSinInteraccion: "16%",
      AddToCartConInteraccion: "2%",
      TransaccionesSinInteraccion: 0.0076,
      TransaccionesConInteraccion: 0.02,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMT24CDBWCCC8",
      sinInteraccion: 361,
      conInteraccion: 40,
      tiempoSinInteraccion: "0:03:22",
      tiempoConInteraccion: "0:08:01",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "23%",
      TransaccionesSinInteraccion: 0.0028,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Aires",
      sku: "MMT18CDBWCCC8",
      sinInteraccion: 298,
      conInteraccion: 31,
      tiempoSinInteraccion: "0:03:42",
      tiempoConInteraccion: "0:02:56",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "29%",
      TransaccionesSinInteraccion: 0.0034,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Calentadores",
      sku: "CAGM20ANS0",
      sinInteraccion: 73,
      conInteraccion: 20,
      tiempoSinInteraccion: "0:04:37",
      tiempoConInteraccion: "0:06:30",
      AddToCartSinInteraccion: "27%",
      AddToCartConInteraccion: "50%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Calentadores",
      sku: "CAGM30ANS0",
      sinInteraccion: 62,
      conInteraccion: 10,
      tiempoSinInteraccion: "0:02:50",
      tiempoConInteraccion: "0:03:27",
      AddToCartSinInteraccion: "29%",
      AddToCartConInteraccion: "60%",
      TransaccionesSinInteraccion: 0.0323,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Calentadores",
      sku: "CAGM10ANS0",
      sinInteraccion: 32,
      conInteraccion: 7,
      tiempoSinInteraccion: "0:00:48",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "38%",
      AddToCartConInteraccion: "86%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Calentadores",
      sku: "CAGM15ANS0",
      sinInteraccion: 26,
      conInteraccion: 7,
      tiempoSinInteraccion: "0:05:55",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "27%",
      AddToCartConInteraccion: "71%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "LMC70203WDAB0",
      sinInteraccion: 762,
      conInteraccion: 234,
      tiempoSinInteraccion: "0:05:47",
      tiempoConInteraccion: "0:04:58",
      AddToCartSinInteraccion: "30%",
      AddToCartConInteraccion: "23%",
      TransaccionesSinInteraccion: 0.0052,
      TransaccionesConInteraccion: 0.0043,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "LMC46100WDAB0",
      sinInteraccion: 572,
      conInteraccion: 136,
      tiempoSinInteraccion: "0:04:02",
      tiempoConInteraccion: "0:03:05",
      AddToCartSinInteraccion: "17%",
      AddToCartConInteraccion: "18%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "LMC75201WDAB0",
      sinInteraccion: 545,
      conInteraccion: 129,
      tiempoSinInteraccion: "0:07:02",
      tiempoConInteraccion: "0:09:56",
      AddToCartSinInteraccion: "22%",
      AddToCartConInteraccion: "15%",
      TransaccionesSinInteraccion: 0.0018,
      TransaccionesConInteraccion: 0.0078,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "LMC70200WDAB1",
      sinInteraccion: 532,
      conInteraccion: 135,
      tiempoSinInteraccion: "0:03:31",
      tiempoConInteraccion: "0:05:31",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "21%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "LMA9020WGAB0",
      sinInteraccion: 451,
      conInteraccion: 38,
      tiempoSinInteraccion: "0:03:32",
      tiempoConInteraccion: "0:04:32",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "3%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "LMA79114VBAB0",
      sinInteraccion: 344,
      conInteraccion: 65,
      tiempoSinInteraccion: "0:03:25",
      tiempoConInteraccion: "0:02:06",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "20%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "MCLC2040GSBB0",
      sinInteraccion: 272,
      conInteraccion: 45,
      tiempoSinInteraccion: "0:03:04",
      tiempoConInteraccion: "0:02:18",
      AddToCartSinInteraccion: "12%",
      AddToCartConInteraccion: "11%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Lavado",
      sku: "DMG17R8MSDAB2",
      sinInteraccion: 154,
      conInteraccion: 60,
      tiempoSinInteraccion: "0:03:19",
      tiempoConInteraccion: "0:06:49",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "17%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA267FYCC",
      sinInteraccion: "2,005",
      conInteraccion: 590,
      tiempoSinInteraccion: "0:05:39",
      tiempoConInteraccion: "0:08:51",
      AddToCartSinInteraccion: "33%",
      AddToCartConInteraccion: "20%",
      TransaccionesSinInteraccion: 0.006,
      TransaccionesConInteraccion: 0.0136,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP384FGCC",
      sinInteraccion: "1,753",
      conInteraccion: 570,
      tiempoSinInteraccion: "0:06:00",
      tiempoConInteraccion: "0:09:40",
      AddToCartSinInteraccion: "30%",
      AddToCartConInteraccion: "24%",
      TransaccionesSinInteraccion: 0.0068,
      TransaccionesConInteraccion: 0.0123,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA313FXCT",
      sinInteraccion: "1,302",
      conInteraccion: 425,
      tiempoSinInteraccion: "0:06:00",
      tiempoConInteraccion: "0:06:15",
      AddToCartSinInteraccion: "26%",
      AddToCartConInteraccion: "22%",
      TransaccionesSinInteraccion: 0.0092,
      TransaccionesConInteraccion: 0.0047,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "MSL521QMLSS0",
      sinInteraccion: "1,488",
      conInteraccion: 380,
      tiempoSinInteraccion: "0:04:25",
      tiempoConInteraccion: "0:06:25",
      AddToCartSinInteraccion: "14%",
      AddToCartConInteraccion: "12%",
      TransaccionesSinInteraccion: 0.004,
      TransaccionesConInteraccion: 0.0105,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMS510IBBQP0",
      sinInteraccion: "1,420",
      conInteraccion: 287,
      tiempoSinInteraccion: "0:04:36",
      tiempoConInteraccion: "0:10:16",
      AddToCartSinInteraccion: "18%",
      AddToCartConInteraccion: "14%",
      TransaccionesSinInteraccion: 0.0028,
      TransaccionesConInteraccion: 0.007,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMB300IZBRP0",
      sinInteraccion: "1,069",
      conInteraccion: 311,
      tiempoSinInteraccion: "0:04:29",
      tiempoConInteraccion: "0:07:49",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0.0065,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMB520IWBQP1",
      sinInteraccion: "1,004",
      conInteraccion: 370,
      tiempoSinInteraccion: "0:03:44",
      tiempoConInteraccion: "0:04:25",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA313FXCC",
      sinInteraccion: "1,037",
      conInteraccion: 307,
      tiempoSinInteraccion: "0:04:31",
      tiempoConInteraccion: "0:08:58",
      AddToCartSinInteraccion: "22%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0.0019,
      TransaccionesConInteraccion: 0.0033,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA267PYCU",
      sinInteraccion: 817,
      conInteraccion: 243,
      tiempoSinInteraccion: "0:07:58",
      tiempoConInteraccion: "0:13:52",
      AddToCartSinInteraccion: "24%",
      AddToCartConInteraccion: "19%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP421FGCT",
      sinInteraccion: 638,
      conInteraccion: 244,
      tiempoSinInteraccion: "0:04:54",
      tiempoConInteraccion: "0:07:58",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "19%",
      TransaccionesSinInteraccion: 0.0031,
      TransaccionesConInteraccion: 0.0041,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA230FJCG1",
      sinInteraccion: 767,
      conInteraccion: 52,
      tiempoSinInteraccion: "0:03:05",
      tiempoConInteraccion: "0:07:14",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMB400IBBRX0",
      sinInteraccion: 457,
      conInteraccion: 149,
      tiempoSinInteraccion: "0:03:18",
      tiempoConInteraccion: "0:04:33",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "13%",
      TransaccionesSinInteraccion: 0.0153,
      TransaccionesConInteraccion: 0.047,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "MCLC2040PPDG0",
      sinInteraccion: 1,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:01:54",
      tiempoConInteraccion: "0:02:37",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP410FZCC1",
      sinInteraccion: 395,
      conInteraccion: 143,
      tiempoSinInteraccion: "0:05:18",
      tiempoConInteraccion: "0:13:05",
      AddToCartSinInteraccion: "26%",
      AddToCartConInteraccion: "15%",
      TransaccionesSinInteraccion: 0.0076,
      TransaccionesConInteraccion: 0.014,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "ALASKAV200S0",
      sinInteraccion: 420,
      conInteraccion: 97,
      tiempoSinInteraccion: "0:03:02",
      tiempoConInteraccion: "0:03:08",
      AddToCartSinInteraccion: "11%",
      AddToCartConInteraccion: "9%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP438FGCT",
      sinInteraccion: 356,
      conInteraccion: 123,
      tiempoSinInteraccion: "0:04:10",
      tiempoConInteraccion: "0:05:01",
      AddToCartSinInteraccion: "15%",
      AddToCartConInteraccion: "11%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA313FZCC",
      sinInteraccion: 235,
      conInteraccion: 112,
      tiempoSinInteraccion: "0:06:00",
      tiempoConInteraccion: "0:08:06",
      AddToCartSinInteraccion: "31%",
      AddToCartConInteraccion: "27%",
      TransaccionesSinInteraccion: 0.0043,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP438FZCU",
      sinInteraccion: 246,
      conInteraccion: 78,
      tiempoSinInteraccion: "0:04:37",
      tiempoConInteraccion: "0:02:52",
      AddToCartSinInteraccion: "18%",
      AddToCartConInteraccion: "10%",
      TransaccionesSinInteraccion: 0.0041,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMF02BRX0",
      sinInteraccion: 264,
      conInteraccion: 42,
      tiempoSinInteraccion: "0:03:25",
      tiempoConInteraccion: "0:03:53",
      AddToCartSinInteraccion: "14%",
      AddToCartConInteraccion: "12%",
      TransaccionesSinInteraccion: 0.0038,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP421FZCC",
      sinInteraccion: 229,
      conInteraccion: 68,
      tiempoSinInteraccion: "0:03:20",
      tiempoConInteraccion: "0:03:54",
      AddToCartSinInteraccion: "17%",
      AddToCartConInteraccion: "15%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMF04BRX0",
      sinInteraccion: 275,
      conInteraccion: 19,
      tiempoSinInteraccion: "0:03:14",
      tiempoConInteraccion: "0:06:52",
      AddToCartSinInteraccion: "7%",
      AddToCartConInteraccion: "26%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP421FYCU",
      sinInteraccion: 189,
      conInteraccion: 64,
      tiempoSinInteraccion: "0:05:30",
      tiempoConInteraccion: "0:03:42",
      AddToCartSinInteraccion: "22%",
      AddToCartConInteraccion: "9%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP438FYCU",
      sinInteraccion: 134,
      conInteraccion: 51,
      tiempoSinInteraccion: "0:10:00",
      tiempoConInteraccion: "0:07:10",
      AddToCartSinInteraccion: "15%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA267FYCT",
      sinInteraccion: 127,
      conInteraccion: 36,
      tiempoSinInteraccion: "0:10:23",
      tiempoConInteraccion: "0:03:13",
      AddToCartSinInteraccion: "24%",
      AddToCartConInteraccion: "17%",
      TransaccionesSinInteraccion: 0.0157,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP384FGCT",
      sinInteraccion: 72,
      conInteraccion: 21,
      tiempoSinInteraccion: "0:05:46",
      tiempoConInteraccion: "0:01:19",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "33%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA250FJCL1",
      sinInteraccion: 105,
      conInteraccion: 39,
      tiempoSinInteraccion: "0:04:53",
      tiempoConInteraccion: "0:06:40",
      AddToCartSinInteraccion: "44%",
      AddToCartConInteraccion: "31%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP365FYCT",
      sinInteraccion: 294,
      conInteraccion: 19,
      tiempoSinInteraccion: "0:05:50",
      tiempoConInteraccion: "0:10:14",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0.0272,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP405FYCU",
      sinInteraccion: 186,
      conInteraccion: 51,
      tiempoSinInteraccion: "0:05:49",
      tiempoConInteraccion: "0:09:43",
      AddToCartSinInteraccion: "20%",
      AddToCartConInteraccion: "24%",
      TransaccionesSinInteraccion: 0.0215,
      TransaccionesConInteraccion: 0.0588,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA250FJCL1",
      sinInteraccion: 105,
      conInteraccion: 39,
      tiempoSinInteraccion: "0:04:53",
      tiempoConInteraccion: "0:06:40",
      AddToCartSinInteraccion: "44%",
      AddToCartConInteraccion: "31%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP425FYCU",
      sinInteraccion: 46,
      conInteraccion: 7,
      tiempoSinInteraccion: "0:05:13",
      tiempoConInteraccion: "0:09:43",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "43%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0.4286,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA310FZCC",
      sinInteraccion: 78,
      conInteraccion: 25,
      tiempoSinInteraccion: "0:06:31",
      tiempoConInteraccion: "0:06:35",
      AddToCartSinInteraccion: "24%",
      AddToCartConInteraccion: "12%",
      TransaccionesSinInteraccion: 0.0385,
      TransaccionesConInteraccion: 0.04,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMP410FZCC",
      sinInteraccion: 64,
      conInteraccion: 6,
      tiempoSinInteraccion: "0:05:22",
      tiempoConInteraccion: "0:13:36",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0469,
      TransaccionesConInteraccion: 0.3333,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "ALASKA430BH",
      sinInteraccion: 144,
      conInteraccion: 16,
      tiempoSinInteraccion: "0:08:30",
      tiempoConInteraccion: "0:17:46",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "19%",
      TransaccionesSinInteraccion: 0.0139,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "RMA305FYCC",
      sinInteraccion: 14,
      conInteraccion: 3,
      tiempoSinInteraccion: "0:02:17",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "7%",
      AddToCartConInteraccion: "33%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Refrigeración",
      sku: "ICMK12X0",
      sinInteraccion: 1,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:07:27",
      tiempoConInteraccion: "0:08:36",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "PM6048GV0",
      sinInteraccion: 691,
      conInteraccion: 102,
      tiempoSinInteraccion: "0:03:21",
      tiempoConInteraccion: "0:06:14",
      AddToCartSinInteraccion: "9%",
      AddToCartConInteraccion: "8%",
      TransaccionesSinInteraccion: 0.0043,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "CM6040NV0",
      sinInteraccion: 317,
      conInteraccion: 49,
      tiempoSinInteraccion: "0:06:11",
      tiempoConInteraccion: "0:18:52",
      AddToCartSinInteraccion: "27%",
      AddToCartConInteraccion: "14%",
      TransaccionesSinInteraccion: 0.0032,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "HM6017GWAI0",
      sinInteraccion: 346,
      conInteraccion: 54,
      tiempoSinInteraccion: "0:03:32",
      tiempoConInteraccion: "0:04:21",
      AddToCartSinInteraccion: "31%",
      AddToCartConInteraccion: "30%",
      TransaccionesSinInteraccion: 0.0145,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "CM6040XV0",
      sinInteraccion: 310,
      conInteraccion: 48,
      tiempoSinInteraccion: "0:04:30",
      tiempoConInteraccion: "0:08:50",
      AddToCartSinInteraccion: "18%",
      AddToCartConInteraccion: "25%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "HM6022EYAI0",
      sinInteraccion: 184,
      conInteraccion: 51,
      tiempoSinInteraccion: "0:03:52",
      tiempoConInteraccion: "0:06:22",
      AddToCartSinInteraccion: "39%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "CM6030PI0",
      sinInteraccion: 113,
      conInteraccion: 24,
      tiempoSinInteraccion: "0:01:37",
      tiempoConInteraccion: "0:00:44",
      AddToCartSinInteraccion: "42%",
      AddToCartConInteraccion: "58%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Empotre",
      sku: "CMG6054LA-0CON",
      sinInteraccion: 26,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:03:21",
      tiempoConInteraccion: "0:00:44",
      AddToCartSinInteraccion: "58%",
      AddToCartConInteraccion: "75%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Estufas",
      sku: "EMC6050NFX0",
      sinInteraccion: 622,
      conInteraccion: 124,
      tiempoSinInteraccion: "0:11:16",
      tiempoConInteraccion: "0:04:39",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Estufas",
      sku: "TX1G-6CON",
      sinInteraccion: 515,
      conInteraccion: 145,
      tiempoSinInteraccion: "0:03:53",
      tiempoConInteraccion: "0:08:57",
      AddToCartSinInteraccion: "19%",
      AddToCartConInteraccion: "7%",
      TransaccionesSinInteraccion: 0.0039,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Colombia",
      categoria: "Globales",
      sku: "AFM38DN",
      sinInteraccion: 444,
      conInteraccion: 44,
      tiempoSinInteraccion: "0:02:46",
      tiempoConInteraccion: "0:06:29",
      AddToCartSinInteraccion: "27%",
      AddToCartConInteraccion: "30%",
      TransaccionesSinInteraccion: 0.0045,
      TransaccionesConInteraccion: 0.0455,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMA300FXMRP0",
      sinInteraccion: "1,486",
      conInteraccion: 600,
      tiempoSinInteraccion: "0:03:38",
      tiempoConInteraccion: "0:05:14",
      AddToCartSinInteraccion: "9%",
      AddToCartConInteraccion: "13%",
      TransaccionesSinInteraccion: 0.0054,
      TransaccionesConInteraccion: 0.0033,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB400IBMRX0",
      sinInteraccion: 461,
      conInteraccion: 227,
      tiempoSinInteraccion: "0:05:44",
      tiempoConInteraccion: "0:09:14",
      AddToCartSinInteraccion: "7%",
      AddToCartConInteraccion: "7%",
      TransaccionesSinInteraccion: 0.0065,
      TransaccionesConInteraccion: 0.0132,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMS510IAMRM0",
      sinInteraccion: 468,
      conInteraccion: 202,
      tiempoSinInteraccion: "0:03:01",
      tiempoConInteraccion: "0:04:37",
      AddToCartSinInteraccion: "18%",
      AddToCartConInteraccion: "26%",
      TransaccionesSinInteraccion: 0.0021,
      TransaccionesConInteraccion: 0.005,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RME360FGMRM0",
      sinInteraccion: 565,
      conInteraccion: 206,
      tiempoSinInteraccion: "0:06:15",
      tiempoConInteraccion: "0:08:01",
      AddToCartSinInteraccion: "9%",
      AddToCartConInteraccion: "16%",
      TransaccionesSinInteraccion: 0.0035,
      TransaccionesConInteraccion: 0.0049,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMA300FJMRM0",
      sinInteraccion: 417,
      conInteraccion: 136,
      tiempoSinInteraccion: "0:03:29",
      tiempoConInteraccion: "0:03:50",
      AddToCartSinInteraccion: "10%",
      AddToCartConInteraccion: "13%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMS400IBMRP0",
      sinInteraccion: 729,
      conInteraccion: 341,
      tiempoSinInteraccion: "0:03:22",
      tiempoConInteraccion: "0:04:38",
      AddToCartSinInteraccion: "9%",
      AddToCartConInteraccion: "12%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB400IBMRP0",
      sinInteraccion: "1,189",
      conInteraccion: 342,
      tiempoSinInteraccion: "0:02:33",
      tiempoConInteraccion: "0:05:34",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "2%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB520IBMRX1",
      sinInteraccion: 585,
      conInteraccion: 257,
      tiempoSinInteraccion: "0:06:28",
      tiempoConInteraccion: "0:08:49",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "7%",
      TransaccionesSinInteraccion: 0.0034,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB520IBMRP1",
      sinInteraccion: 527,
      conInteraccion: 50,
      tiempoSinInteraccion: "0:00:52",
      tiempoConInteraccion: "0:04:30",
      AddToCartSinInteraccion: "11%",
      AddToCartConInteraccion: "80%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMS510ICMRP0",
      sinInteraccion: "1,075",
      conInteraccion: 436,
      tiempoSinInteraccion: "0:04:18",
      tiempoConInteraccion: "0:08:38",
      AddToCartSinInteraccion: "3%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0.0009,
      TransaccionesConInteraccion: 0.0023,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RME360FZMRP0",
      sinInteraccion: "1,145",
      conInteraccion: 414,
      tiempoSinInteraccion: "0:02:57",
      tiempoConInteraccion: "0:07:03",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "10%",
      TransaccionesSinInteraccion: 0.0035,
      TransaccionesConInteraccion: 0.0024,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RME360FDMRD0",
      sinInteraccion: 182,
      conInteraccion: 68,
      tiempoSinInteraccion: "0:04:47",
      tiempoConInteraccion: "0:04:35",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "9%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB520IWMRX1",
      sinInteraccion: 544,
      conInteraccion: 251,
      tiempoSinInteraccion: "0:03:40",
      tiempoConInteraccion: "0:06:35",
      AddToCartSinInteraccion: "8%",
      AddToCartConInteraccion: "9%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB300IZMRP0",
      sinInteraccion: 292,
      conInteraccion: 88,
      tiempoSinInteraccion: "0:03:56",
      tiempoConInteraccion: "0:04:43",
      AddToCartSinInteraccion: "3%",
      AddToCartConInteraccion: "2%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Refrigeración",
      sku: "RMB520IWMRP1",
      sinInteraccion: "1,046",
      conInteraccion: 485,
      tiempoSinInteraccion: "0:04:31",
      tiempoConInteraccion: "0:05:21",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "9%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Empotre",
      sku: "WEM7643CSIS0",
      sinInteraccion: 563,
      conInteraccion: 289,
      tiempoSinInteraccion: "0:04:18",
      tiempoConInteraccion: "0:05:11",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "8%",
      TransaccionesSinInteraccion: 0.0018,
      TransaccionesConInteraccion: 0.0035,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Empotre",
      sku: "XOC80800CT2",
      sinInteraccion: 303,
      conInteraccion: 101,
      tiempoSinInteraccion: "0:05:08",
      tiempoConInteraccion: "0:09:13",
      AddToCartSinInteraccion: "8%",
      AddToCartConInteraccion: "14%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Empotre",
      sku: "IO8084GETSS0",
      sinInteraccion: 5,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:04:53",
      tiempoConInteraccion: "0:07:36",
      AddToCartSinInteraccion: "12%",
      AddToCartConInteraccion: "17%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Empotre",
      sku: "XOC80790CT2",
      sinInteraccion: 206,
      conInteraccion: 86,
      tiempoSinInteraccion: "0:06:44",
      tiempoConInteraccion: "0:08:07",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "2%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Empotre",
      sku: "IO8063GEGSS0",
      sinInteraccion: 139,
      conInteraccion: 61,
      tiempoSinInteraccion: "0:03:33",
      tiempoConInteraccion: "0:02:51",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "7%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EMH7612DSS0",
      sinInteraccion: 569,
      conInteraccion: 137,
      tiempoSinInteraccion: "0:03:07",
      tiempoConInteraccion: "0:06:55",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "1%",
      TransaccionesSinInteraccion: 0.0072,
      TransaccionesConInteraccion: 0.0073,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EM7654BFIS2",
      sinInteraccion: 644,
      conInteraccion: 286,
      tiempoSinInteraccion: "0:04:00",
      tiempoConInteraccion: "0:08:42",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "8%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EM7646BSIS2",
      sinInteraccion: 453,
      conInteraccion: 219,
      tiempoSinInteraccion: "0:07:06",
      tiempoConInteraccion: "0:10:58",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "11%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EM7657CSIS2",
      sinInteraccion: 250,
      conInteraccion: 105,
      tiempoSinInteraccion: "0:03:59",
      tiempoConInteraccion: "0:08:23",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "3%",
      TransaccionesSinInteraccion: 0.0044,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EM7620BAIS2",
      sinInteraccion: 623,
      conInteraccion: 220,
      tiempoSinInteraccion: "0:05:09",
      tiempoConInteraccion: "0:07:57",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "5%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EMH7614DATMSX0",
      sinInteraccion: 294,
      conInteraccion: 92,
      tiempoSinInteraccion: "0:10:09",
      tiempoConInteraccion: "0:31:20",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "5%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EMH7614DATBS0",
      sinInteraccion: 76,
      conInteraccion: 26,
      tiempoSinInteraccion: "0:06:42",
      tiempoConInteraccion: "0:09:54",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EMH7614DATSS0",
      sinInteraccion: 179,
      conInteraccion: 67,
      tiempoSinInteraccion: "0:01:50",
      tiempoConInteraccion: "0:04:22",
      AddToCartSinInteraccion: "3%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EMH7602JBS0",
      sinInteraccion: 697,
      conInteraccion: 291,
      tiempoSinInteraccion: "0:03:38",
      tiempoConInteraccion: "0:06:04",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "2%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Estufas",
      sku: "EMH7613DATSS0",
      sinInteraccion: 179,
      conInteraccion: 75,
      tiempoSinInteraccion: "0:04:42",
      tiempoConInteraccion: "0:07:19",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMA71214VBAB0",
      sinInteraccion: 312,
      conInteraccion: 111,
      tiempoSinInteraccion: "0:02:41",
      tiempoConInteraccion: "0:05:36",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMH72211WDAB0",
      sinInteraccion: 133,
      conInteraccion: 61,
      tiempoSinInteraccion: "0:04:56",
      tiempoConInteraccion: "0:07:49",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "8%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "MCL2040PPDG1",
      sinInteraccion: 958,
      conInteraccion: 200,
      tiempoSinInteraccion: "0:02:03",
      tiempoConInteraccion: "0:06:00",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "11%",
      TransaccionesSinInteraccion: 0.001,
      TransaccionesConInteraccion: 0.005,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMH72201WBAB1",
      sinInteraccion: 381,
      conInteraccion: 116,
      tiempoSinInteraccion: "0:03:29",
      tiempoConInteraccion: "0:05:53",
      AddToCartSinInteraccion: "3%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMH72205WDAB1",
      sinInteraccion: 88,
      conInteraccion: 19,
      tiempoSinInteraccion: "0:01:11",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "11%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMA74215WBAB1",
      sinInteraccion: 603,
      conInteraccion: 187,
      tiempoSinInteraccion: "0:03:22",
      tiempoConInteraccion: "0:06:17",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMA74215WDAB1",
      sinInteraccion: 406,
      conInteraccion: 190,
      tiempoSinInteraccion: "0:04:10",
      tiempoConInteraccion: "0:07:12",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMH74201WDAB1",
      sinInteraccion: 185,
      conInteraccion: 72,
      tiempoSinInteraccion: "0:03:11",
      tiempoConInteraccion: "0:02:09",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMP75205WDAB0",
      sinInteraccion: 481,
      conInteraccion: 160,
      tiempoSinInteraccion: "0:05:33",
      tiempoConInteraccion: "0:07:32",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "4%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "MCL2040PSDG0",
      sinInteraccion: 565,
      conInteraccion: 113,
      tiempoSinInteraccion: "0:02:38",
      tiempoConInteraccion: "0:04:41",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "15%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "DMG17R8MSDAB2",
      sinInteraccion: 119,
      conInteraccion: 25,
      tiempoSinInteraccion: "0:04:00",
      tiempoConInteraccion: "0:04:41",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "8%",
      TransaccionesSinInteraccion: 0.0168,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "SMG47N5MSBAB0",
      sinInteraccion: 507,
      conInteraccion: 95,
      tiempoSinInteraccion: "0:02:52",
      tiempoConInteraccion: "0:07:16",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "2%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "SMG47N8MSBAB0",
      sinInteraccion: 196,
      conInteraccion: 33,
      tiempoSinInteraccion: "0:00:58",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "DMG47N8MSDAB0",
      sinInteraccion: 78,
      conInteraccion: 16,
      tiempoSinInteraccion: "0:00:58",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "SMG47N8MSDAB0",
      sinInteraccion: 308,
      conInteraccion: 80,
      tiempoSinInteraccion: "0:01:55",
      tiempoConInteraccion: "0:03:10",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0.0032,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Lavado",
      sku: "LMP75201WDAB0",
      sinInteraccion: "21,594",
      conInteraccion: 308,
      tiempoSinInteraccion: "0:01:05",
      tiempoConInteraccion: "0:04:07",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "10%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Globales",
      sku: "AFM38DN",
      sinInteraccion: 289,
      conInteraccion: 71,
      tiempoSinInteraccion: "0:02:13",
      tiempoConInteraccion: "0:05:13",
      AddToCartSinInteraccion: "8%",
      AddToCartConInteraccion: "5%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "México",
      categoria: "Globales",
      sku: "CHM11BPL5",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Campanas",
      sku: "CM6045XV0",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "HM6018EXAI",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "CMG6044SD",
      sinInteraccion: 1168,
      conInteraccion: 21,
      tiempoSinInteraccion: "0:03:29",
      tiempoConInteraccion: "0:07:40",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "10%",
      TransaccionesSinInteraccion: 0.0188,
      TransaccionesConInteraccion: 0.0476,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "ANDES7650FX1",
      sinInteraccion: 167,
      conInteraccion: 10,
      tiempoSinInteraccion: "0:02:46",
      tiempoConInteraccion: "0:05:08",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "CMC5550AX0",
      sinInteraccion: 361,
      conInteraccion: 26,
      tiempoSinInteraccion: "0:03:02",
      tiempoConInteraccion: "0:06:39",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0083,
      TransaccionesConInteraccion: 0.0385,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "CMC20AXX",
      sinInteraccion: 482,
      conInteraccion: 18,
      tiempoSinInteraccion: "0:03:02",
      tiempoConInteraccion: "0:06:39",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "6%",
      TransaccionesSinInteraccion: 0.0062,
      TransaccionesConInteraccion: 0.0556,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "CMC5110AX0",
      sinInteraccion: 294,
      conInteraccion: 24,
      tiempoSinInteraccion: "0:03:00",
      tiempoConInteraccion: "0:06:40",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "25%",
      TransaccionesSinInteraccion: 0.0204,
      TransaccionesConInteraccion: 0.0417,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Estufas",
      sku: "CMC20ABX",
      sinInteraccion: 741,
      conInteraccion: 12,
      tiempoSinInteraccion: "0:02:35",
      tiempoConInteraccion: "0:06:31",
      AddToCartSinInteraccion: "3%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0054,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Empotre",
      sku: "HM6018EXAI0",
      sinInteraccion: 251,
      conInteraccion: 1,
      tiempoSinInteraccion: "0:03:00",
      tiempoConInteraccion: "0:06:10",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Lavado",
      sku: "SEM101BDBY",
      sinInteraccion: 2651,
      conInteraccion: 89,
      tiempoSinInteraccion: "0:02:44",
      tiempoConInteraccion: "0:06:46",
      AddToCartSinInteraccion: "7%",
      AddToCartConInteraccion: "1%",
      TransaccionesSinInteraccion: 0.0094,
      TransaccionesConInteraccion: 0.0337,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Lavado",
      sku: "MCL2040EEBBY0",
      sinInteraccion: 2209,
      conInteraccion: 30,
      tiempoSinInteraccion: "0:02:56",
      tiempoConInteraccion: "0:05:09",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "13%",
      TransaccionesSinInteraccion: 0.0014,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Lavado",
      sku: "LMA0920WGCL0",
      sinInteraccion: 436,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:02:56",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "3%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0229,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Lavado",
      sku: "SMG26N5MNBCL1",
      sinInteraccion: 129,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:05:17",
      tiempoConInteraccion: "0:03:39",
      AddToCartSinInteraccion: "6%",
      AddToCartConInteraccion: "75%",
      TransaccionesSinInteraccion: 0.0543,
      TransaccionesConInteraccion: 0.25,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMF04LRX0",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "MSC518LKRSS0",
      sinInteraccion: 160,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:04:53",
      tiempoConInteraccion: "0:04:04",
      AddToCartSinInteraccion: "7%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.025,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "FDHM150BY2",
      sinInteraccion: 747,
      conInteraccion: 1,
      tiempoSinInteraccion: "0:03:08",
      tiempoConInteraccion: "0:01:39",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0013,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMA250PHUG1",
      sinInteraccion: 136,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:02:38",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "1%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMS510IBLRP0",
      sinInteraccion: 244,
      conInteraccion: 12,
      tiempoSinInteraccion: "0:02:42",
      tiempoConInteraccion: "0:12:17",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "8%",
      TransaccionesSinInteraccion: 0.0041,
      TransaccionesConInteraccion: 0.0833,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMP410FZUU",
      sinInteraccion: 661,
      conInteraccion: 30,
      tiempoSinInteraccion: "0:02:05",
      tiempoConInteraccion: "0:05:53",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMP410FZUC",
      sinInteraccion: 922,
      conInteraccion: 32,
      tiempoSinInteraccion: "0:02:09",
      tiempoConInteraccion: "0:05:50",
      AddToCartSinInteraccion: "5%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMF02LRX0",
      sinInteraccion: 654,
      conInteraccion: 27,
      tiempoSinInteraccion: "0:03:19",
      tiempoConInteraccion: "0:08:17",
      AddToCartSinInteraccion: "4%",
      AddToCartConInteraccion: "26%",
      TransaccionesSinInteraccion: 0.0122,
      TransaccionesConInteraccion: 0.1111,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMB300IZLRP0",
      sinInteraccion: 58,
      conInteraccion: 2,
      tiempoSinInteraccion: "0:02:56",
      tiempoConInteraccion: "0:00:46",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0172,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMA300FWUT",
      sinInteraccion: 276,
      conInteraccion: 36,
      tiempoSinInteraccion: "0:02:46",
      tiempoConInteraccion: "0:03:00",
      AddToCartSinInteraccion: "9%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMA300FWUC",
      sinInteraccion: 235,
      conInteraccion: 36,
      tiempoSinInteraccion: "0:06:33",
      tiempoConInteraccion: "0:09:00",
      AddToCartSinInteraccion: "8%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0.0128,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMA255PYUU",
      sinInteraccion: 1097,
      conInteraccion: 38,
      tiempoSinInteraccion: "0:03:31",
      tiempoConInteraccion: "0:06:42",
      AddToCartSinInteraccion: "2%",
      AddToCartConInteraccion: "11%",
      TransaccionesSinInteraccion: 0.0055,
      TransaccionesConInteraccion: 0.0263,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "RMP400FHUG1",
      sinInteraccion: 43,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:06:39",
      tiempoConInteraccion: "0:04:11",
      AddToCartSinInteraccion: "7%",
      AddToCartConInteraccion: "50%",
      TransaccionesSinInteraccion: 0.0698,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Chile",
      categoria: "Refrigeración",
      sku: "MCL2040EEDGY0",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "0%",
      AddToCartConInteraccion: "0%",
      TransaccionesSinInteraccion: 0,
      TransaccionesConInteraccion: 0,
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Aires",
      sku: "MMT18CDBWCCC8",
      sinInteraccion: 12,
      conInteraccion: 5,
      tiempoSinInteraccion: "0:03:27",
      tiempoConInteraccion: "0:01:53",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Aires",
      sku: "MMT12CDBWCCC8",
      sinInteraccion: 2,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:02:05",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Congelador",
      sku: "CHM430PB2",
      sinInteraccion: 16,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:07:15",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Empotre",
      sku: "HM6022EYAI0",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Empotre",
      sku: "CMG6054LC-1PE",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Empotre",
      sku: "CMU6020PI0",
      sinInteraccion: 12,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:04:27",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Empotre",
      sku: "CMU6020PB0",
      sinInteraccion: 20,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:02:49",
      tiempoConInteraccion: "0:00:45",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Empotre",
      sku: "CM9016PI0",
      sinInteraccion: 0,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:00:00",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Lavado",
      sku: "CLME70204BBB0",
      sinInteraccion: 19,
      conInteraccion: 3,
      tiempoSinInteraccion: "0:02:29",
      tiempoConInteraccion: "0:02:37",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Lavado",
      sku: "LMA70200WDBB1",
      sinInteraccion: 4,
      conInteraccion: 1,
      tiempoSinInteraccion: "0:02:58",
      tiempoConInteraccion: "0:02:21",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Lavado",
      sku: "LMA48100WDBB0",
      sinInteraccion: 27,
      conInteraccion: 2,
      tiempoSinInteraccion: "0:06:18",
      tiempoConInteraccion: "0:01:46",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Lavado",
      sku: "LMAP4120WGABB0",
      sinInteraccion: 1,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:03:40",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMS510IBPRP0",
      sinInteraccion: 11,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:03:00",
      tiempoConInteraccion: "0:04:48",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMP425FJPT",
      sinInteraccion: 23,
      conInteraccion: 3,
      tiempoSinInteraccion: "0:07:36",
      tiempoConInteraccion: "0:03:02",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMP405FYPU",
      sinInteraccion: 2,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:04:13",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMP410FZPC",
      sinInteraccion: "3,092",
      conInteraccion: 4,
      tiempoSinInteraccion: "0:01:02",
      tiempoConInteraccion: "0:07:02",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMF04PRX0",
      sinInteraccion: 42,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:02:09",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMB300IZPRP0",
      sinInteraccion: 19,
      conInteraccion: 4,
      tiempoSinInteraccion: "0:04:15",
      tiempoConInteraccion: "0:01:48",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMA305FWPT",
      sinInteraccion: 38,
      conInteraccion: 3,
      tiempoSinInteraccion: "0:02:40",
      tiempoConInteraccion: "0:17:40",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMA305FWPC",
      sinInteraccion: 56,
      conInteraccion: 8,
      tiempoSinInteraccion: "0:03:42",
      tiempoConInteraccion: "0:04:37",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "RMA310FZPC",
      sinInteraccion: 42,
      conInteraccion: 3,
      tiempoSinInteraccion: "0:03:45",
      tiempoConInteraccion: "0:02:05",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "CLMG70204DBB0",
      sinInteraccion: 14,
      conInteraccion: 0,
      tiempoSinInteraccion: "0:01:22",
      tiempoConInteraccion: "0:00:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    },
    {
      pais: "Perú",
      categoria: "Refrigeración",
      sku: "CLPG70204DBB0",
      sinInteraccion: 51,
      conInteraccion: 38,
      tiempoSinInteraccion: "0:03:42",
      tiempoConInteraccion: "0:05:00",
      AddToCartSinInteraccion: "Nul",
      AddToCartConInteraccion: "Nul",
      TransaccionesSinInteraccion: "Nul",
      TransaccionesConInteraccion: "Nul",
      Mes: "Marzo"
    }
  ]
export default dataGeneralxsku